### PR TITLE
Re-enabled the 24 ARM minions

### PR DESCRIPTION
**Pull request by Bischoff**
Move all 24 minions from `overdrive3` and `overdrive4` to suma-arm

(We were missing IP and MAC addresses for 5.0 Provo -- added them)

### CODE REVIEW

**Comment by nodeg** [comment]
```bash
╷
│ Error: Unsupported argument
│ 
│   on main.tf line 706, in module "opensuse155arm-minion":
│  706:   overwrite_fqdn     = "suma-bv-43-min-opensuse155arm.mgr.suse.de"
│ 
│ An argument named "overwrite_fqdn" is not expected here.
╵
Error: Terraform exited with code 1.
Error: Process completed with exit code 1.```

**Comment by Bischoff** [comment]
> ```shell
> ╷
> │ Error: Unsupported argument
> │ 
> │   on main.tf line 706, in module "opensuse155arm-minion":
> │  706:   overwrite_fqdn     = "suma-bv-43-min-opensuse155arm.mgr.suse.de"
> │ 
> │ An argument named "overwrite_fqdn" is not expected here.
> ╵
> Error: Terraform exited with code 1.
> Error: Process completed with exit code 1.```
> ```

yes. on it.

**Review by nodeg — APPROVED** [review]
LGTM, although I did not check the MAC addresses.

**Review by ktsamis — APPROVED** [review]

**Comment by Bischoff** [comment]
> LGTM, although I did not check the MAC addresses.

You did well, as they were wrong :trollface: .

I fixed them in infra now and it matches here (well, normally...).

**Pull request merged**
