### PR TITLE
Filter the output of the terraform apply command to make it more readable

### PR DESCRIPTION
**Pull request by srbarrios**
This PR change (**ONLY in pipeline.groovy for now**) the output of the terraform apply command to make it more readable.

Example:

Previous output:
```
[2024-09-30T08:07:09.425Z] Resource instance example_resource has been created.
[2024-09-30T08:18:36.562Z] module.cucumber_testsuite.module.controller.module.controller.module.host.null_resource.provisioning[0] (remote-exec): <some_random_commands>
```

New output:
```
[08:07:09] Resource instance example_resource has been created.
[08:18:36] cucumber_testsuite.controller (remote-exec): <some_random_commands>
```

WARNING
----

⚠️ 
It has an issue to fix. It doesn't handle properly terraform deployment issues.
image

### CODE REVIEW

**Comment by szachovy** [comment]
> It has an issue to fix. It doesn't handle properly terraform deployment issues.
But we are still able to checkout temporary shell scripts that are failing?

**Comment by srbarrios** [comment]
> > It has an issue to fix. It doesn't handle properly terraform deployment issues.
> 
> But we are still able to checkout temporary shell scripts that are failing?

I don't really get what you mean. But this will not change the behavior in terraform, it just filter the text shown in the console output.

**Review by Bischoff — APPROVED** [review]

**Comment by szachovy** [comment]
> > > It has an issue to fix. It doesn't handle properly terraform deployment issues.
> > 
> > 
> > But we are still able to checkout temporary shell scripts that are failing?
> 
> I don't really get what you mean. But this will not change the behavior in terraform, it just filter the text shown in the console output.

Ok, approving, if it would filter out the scripts that are failing we will see.

**Review by szachovy — APPROVED** [review]

**Review by NamelessOne91 — APPROVED** [review]

**Comment by maximenoel8** [comment]
Did you check that a failing deployment is correctly failing the stage ? Otherwise looks good.

**Pull request merged**
