### PR TITLE
Add Debian 12

### PR DESCRIPTION
**Pull request by Bischoff**
We start supporting Debian 12 in 4.3.9

### CODE REVIEW

**Review by srbarrios — APPROVED** [review]
Approved. I did not review the corresponding MAC addresses.

**Review by nodeg — APPROVED** [review]
LGTM.

**Comment by Bischoff** [comment]
> LGTM, although I see
> 
> ```shell
> Success! The configuration is valid.
> 
> /home/runner/work/_temp/29676fe7-8dfa-47d9-bc2b-e08b4566ea99/terraform-bin plan -input=false
> ╷
> │ Error: Unsupported attribute
> │ 
> │   on main.tf line 717, in output "aws_mirrors_public_name":
> │  717:   value = module.mirror.configuration.public_names
> │     ├────────────────
> │     │ module.mirror.configuration is object with 3 attributes
> │ 
> │ This object does not have an attribute named "public_names".
> ╵
> Error: Terraform exited with code 1.
> Error: Process completed with exit code 1.
> ```

ok I will comment it out in AWS.

**Comment by Bischoff** [comment]
> Approved. I did not review the corresponding MAC addresses.

I verified them several times. But a mistake is always possible...

**Pull request merged**
