### PR TITLE
Setup min-build VM

### PR DESCRIPTION
**Pull request by calancha**
Update terraform config. files to use the new min-build VM.
(This PR complements https://github.com/uyuni-project/uyuni/pull/2198)

### CODE REVIEW

**Comment by srbarrios** [comment]
Guessing you added the MAC address to the DHCP, and they are not colliding with others.
LGTM

**Comment by srbarrios** [comment]
> > Guessing you added the MAC address to the DHCP, and they are not colliding with others.
> LGTM
> 
> And the DNS records as well.
> 
> Both are needed at gitlab's infrastructure repository.
> 
> If it's done, then PR LGTM.

As far as I remember, the MAC address are used to stick a MAC with a hostname, at DHCP level
But you don't set up MAC addresses in the DNS 🤔

**Comment by juliogonzalez** [comment]
> As far as I remember, the MAC address are used to stick a MAC with a hostname, at DHCP level
> But you don't set up MAC addresses in the DNS thinking

You don't add MAC addresses to the DNS server. That's right.

But if you add a MAC address to DHCP, you will have a static IP, and if you have a static IP, probably you want a new DNS record for the instance on the environment, right?

So in general, if you add new instances, you should consider both DHCP and DNS.

**Comment by juliogonzalez** [comment]
> As far as I remember, the MAC address are used to stick a MAC with a hostname

An IP, not a hostname.

**Comment by calancha** [comment]
Pushing a commi to make the MAC's uniq.

**Comment by calancha** [comment]
Squashing the 3 commits into 1.

**Comment by Bischoff** [comment]
Changes at Provo dropped, let's start at NUE first.

**Pull request merged**
