### PR TITLE
Remove java checkstyle in Jenkins

### PR DESCRIPTION
**Pull request by jordimassaguerpla**
This is done now as a Github Action.

Fixes https://github.com/SUSE/spacewalk/issues/12892

Signed-off-by: Jordi Massaguer Pla <jmassaguerpla@suse.de>

### CODE REVIEW

**Comment by jordimassaguerpla** [comment]
@srbarrios If I remove this from the context, is there anything else left to do to disable the java checkstyle in the PR ?

**Comment by jordimassaguerpla** [comment]
Testing PRs:

Before

https://github.com/uyuni-project/uyuni/pull/2834

After

https://github.com/uyuni-project/uyuni/pull/2833

**Comment by jordimassaguerpla** [comment]
A PR to test https://github.com/uyuni-project/uyuni/pull/2837

**Comment by jordimassaguerpla** [comment]
@srbarrios I don't see an easy way to test this without merging it... do you know how to easily test it?

**Comment by jordimassaguerpla** [comment]
> @srbarrios If I remove this from the context, is there anything else left to do to disable the java checkstyle in the PR ?

Is disabling this one the thing left to do https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-java_lint_checkstyle-pipeline/ ?

**Comment by srbarrios** [comment]
> > @srbarrios If I remove this from the context, is there anything else left to do to disable the java checkstyle in the PR ?
> 
> Is disabling this one the thing left to do https://ci.suse.de/view/Manager/view/Uyuni-PRs/job/uyuni-prs-java_lint_checkstyle-pipeline/ ?

Exactly, disable or directly delete it.
And also delete the definition of that pipeline : 
https://github.com/SUSE/susemanager-ci/blob/master/jenkins_pipelines/uyuni_prs/Jenkinsfile_prs_javascript_lint

**Review by srbarrios — APPROVED** [review]
Once you delete the pipeline commented on that PR, lgtm.

**Pull request merged**
