### PR TITLE
Refactor BV to have stage always apparent

### PR DESCRIPTION
**Pull request by maximenoel8**
### What does this PR change ?
Move the if condition inside the stage definition to have the stage always visible even when skip.
Split `Prepare stage` into stages corresponding to Jenkins parameters for Proxy and Monitoring.
Add node name into generic stage name.

### CODE REVIEW

**Review by srbarrios — APPROVED** [review]
It's a matter of taste. I'm fine approving this.

**Comment by Bischoff** [comment]
> It's a matter of taste. I'm fine approving this.

If some stages are apparent in a run, and others not, then you view only latest run - jenkins cannot cope with changing columns.

For me it's important to see all runs and be able to compare them. So yes it's a matter of tastes, but it's also conditioned by the way of working.

**Review by Bischoff — APPROVED** [review]

**Comment by maximenoel8** [comment]
Maybe at the end we just need one drop list parameter with Eric / Maxime / Oscar option ;-)

**Comment by maximenoel8** [comment]
After my testing, if some stages are failing, it will not show all the stages ( like all the other pipeline ). And so it will not display the previous run correctly in the main Jenkins view. But like I explain to Eric, the best way to read the parameter is in Blue Ocean.

**Pull request merged**
