### PR TITLE
Add jenkins job for running spacecmd unit tests

### PR DESCRIPTION
**Pull request by isbm**
Add jenkins runner for spacecmd tests

### CODE REVIEW

**Comment by juliogonzalez** [comment]
@srbarrios to be honest, I don't even know what I should address. I remember there's a gitarro PR pending, and then https://github.com/SUSE/susemanager-ci/pull/45.

IIRC we need both merged, and then the gitarro gem released (that's my part of the job).

What else?

**Comment by srbarrios** [comment]
> @srbarrios to be honest, I don't even know what I should address. I remember there's a gitarro PR pending, and then #45.
> 
> IIRC we need both merged, and then the gitarro gem released (that's my part of the job).
> 
> What else?

Working on it now. Nothing else @juliogonzalez I just wonder if you could finish it :)
I'll let you know when we unblock gitarro PR, so we unblock those.

**Comment by srbarrios** [comment]
@isbm after you create the proper jenkins job for the new test in https://ci.suse.de/view/Manager/view/Uyuni-PRs/ you can merge that PR.

If that test make sense in spacewalk repo, I would suggest doing all in once on that PR. That's the folder for SUMA https://ci.suse.de/view/Manager/view/Manager-prs/

**Comment by srbarrios** [comment]
Hi @isbm, it's a pity to don't have running those unit tests yet. It still missing the Jenkins job and probably another pipeline for the spacewalk. Keep it in mind, for when you have some free time :)

**Pull request merged**
