### PR TITLE
Replace CentOS 7 with Rocky 8 on Uyuni/HEAD

### PR DESCRIPTION
**Pull request by nodeg**
**Only merge together with the other PRs mentioned in https://github.com/SUSE/spacewalk/issues/12595**

This will

- replace CentOS 7 with Rocky 8 on Uyuni/HEAD

### CODE REVIEW

**Review by Bischoff — CHANGES_REQUESTED** [review]
the line about tests on PRs is certainly wrong

apart from that, LGTM

**Review by Bischoff — APPROVED** [review]
thanks

**Comment by nodeg** [comment]
Yes, git did not amended what I recently did. Fixed now.

**Comment by nodeg** [comment]
Rebase done.

**Review by srbarrios — CHANGES_REQUESTED** [review]
What about:
[Uyuni-Master-refenv-NUE.tf](https://github.com/SUSE/susemanager-ci/blob/master/terracumber_config/tf_files/Uyuni-Master-refenv-NUE.tf)
[Uyuni-Master-AWS.tf](https://github.com/SUSE/susemanager-ci/blob/master/terracumber_config/tf_files/Uyuni-Master-AWS.tf)
[Uyuni-Master-tests-coverage.tf](https://github.com/SUSE/susemanager-ci/blob/master/terracumber_config/tf_files/Uyuni-Master-tests-coverage.tf)
[SUSEManager-Head-refenv-NUE.tf](https://github.com/SUSE/susemanager-ci/blob/master/terracumber_config/tf_files/SUSEManager-Head-refenv-NUE.tf)

Well, every main.tf that has as product_version uyuni-xxx or head

**Comment by nodeg** [comment]
Fixed. `[Uyuni-Master-tests-coverage.tf](https://github.com/SUSE/susemanager-ci/blob/master/terracumber_config/tf_files/Uyuni-Master-tests-coverage.tf)` does not contain a Red Hat-like minion.

**Review by Bischoff — APPROVED** [review]

**Pull request merged**
