### PR TITLE
Add Rocky 9

### PR DESCRIPTION
**Pull request by Bischoff**
Note: this assumes changes to sumaform.

Those changes are on their way too.

### CODE REVIEW

**Review by ktsamis — APPROVED** [review]

**Review by nodeg — APPROVED** [review]
Not sure about the MAC addresses (I trust you here), but the rest LGTM.

**Review by srbarrios — APPROVED** [review]
LGTM, don't forget minima mirrors too. (For Rocky9 official images)

**Comment by Bischoff** [comment]
> LGTM, don't forget minima mirrors too. (For Rocky9 official images)

on my TODO list already: https://github.com/SUSE/spacewalk/issues/18474#issuecomment-1311890878

**Comment by Bischoff** [comment]
> Not sure about the MAC addresses (I trust you here), but the rest LGTM.

The MAC addresses are defined in gitlab's galaxy/infrastructure, in dhcpd.conf. I copied them directly from there.

**Pull request merged**
