### PR TITLE
Add Retail to BV Jenkins pipeline for 4.3/4.2

### PR DESCRIPTION
**Pull request by nodeg**
Fixes https://github.com/SUSE/spacewalk/issues/17973

### CODE REVIEW

**Review by vandabarata — APPROVED** [review]

**Review by Bischoff — APPROVED** [review]
it looks good, but I am no real expert for pipelines :-( 

we must probably just test and fix at the end of 4.3.1

**Review by jordimassaguerpla — APPROVED** [review]
I am not familiar with this pipeline specifically ... still I have not spotted any "weird" thing, so I agree with Eric, merge and try, and fix if needed afterwards.

**Comment by jordimassaguerpla** [comment]
On a second thought ... you are adding a new feature that was not there. You could add that and by default have it disabled, so you can try it without breaking the actual workflow, and then, once you are sure this works, you can make it enabled by default. Just a suggestion.

**Comment by jordimassaguerpla** [comment]
like a feature flag on trunk based development https://trunkbaseddevelopment.com/feature-flags/ ... so you merge the new code in master but disabled, and when you are sure, you only have to enable it.

**Comment by Bischoff** [comment]
> On a second thought ... you are adding a new feature that was not there. You could add that and by default have it disabled, so you can try it without breaking the actual workflow, and then, once you are sure this works, you can make it enabled by default. Just a suggestion.

the actual workflow is only ran by hand....

so it being "disabled" does not change much

**Comment by jordimassaguerpla** [comment]
> > On a second thought ... you are adding a new feature that was not there. You could add that and by default have it disabled, so you can try it without breaking the actual workflow, and then, once you are sure this works, you can make it enabled by default. Just a suggestion.
> 
> the current workflow is only ran by hand in this case...
> 
> so it being "disabled" does not change much

ok. Then go ahead merging :)

**Comment by nodeg** [comment]
Thanks Jordi!

**Pull request merged**
