### PR TITLE
Use better name for hosts in testsuite module

### PR DESCRIPTION
**Pull request by Bischoff**
sumaform: uyuni-project/sumaform#734
terracumber: https://gitlab.suse.de/juliogonzalezgil/terracumber/-/merge_requests/7

### CODE REVIEW

**Comment by Bischoff** [comment]
> Generally - I like the changes :-) I am only thinking about using "redhat" as a part of the name. What about using something like "rhel-family" instead of it? I understand it is longer, but it also covers cases when we use Centos etc.

"RHEL" stands for "RedHat Enterprise Linux" and it's a specific product from RedHat.

Yes, what is implied there is a "family" of products. For example "suse" family includes "openSUSE" product even though it's not controlled by SUSE as a company. If any, it would then be "redhat-family" and would include CentOS, Fedora, SLES ES, etc. I was tempted to add "family" to make it explicit but I was afraid it was becoming a bit too long.

**Comment by lkotek** [comment]
> > Generally - I like the changes :-) I am only thinking about using "redhat" as a part of the name. What about using something like "rhel-family" instead of it? I understand it is longer, but it also covers cases when we use Centos etc.
> 
> "RHEL" stands for "RedHat Enterprise Linux" and it's a specific product from RedHat.
> 
> Yes, what is implied there is a "family" of products. For example "suse" family includes "openSUSE" product even though it's not controlled by SUSE as a company. If any, it would then be "redhat-family" and would include CentOS, Fedora, SLES ES, etc. I was tempted to add "family" to make it explicit but I was afraid it was becoming a bit too long.

OK, I understand your point. Let's keep it as it is then :)

**Comment by Bischoff** [comment]
> OK, I understand your point. Let's keep it as it is then :)

Oscar seems to share your view, based on `ID_LIKE` field of https://www.freedesktop.org/software/systemd/man/os-release.html .

I can follow the majority and rename `redhat`to `rhel` 😸  .

**Comment by Bischoff** [comment]
Changed my mind:

Salt uses "Debian" and "RedHat" as families 🙂
```
{% elif grains['os_family'] == 'RedHat' %}
```

**Comment by srbarrios** [comment]
> Changed my mind:
> 
> Salt uses "Debian" and "RedHat" as families 🙂
> 
> ```
> {% elif grains['os_family'] == 'RedHat' %}
> ```

To be concrete, the salt states on sunaform use this text as family ;)

**Comment by Bischoff** [comment]
> > Changed my mind:
> > ```
> > {% elif grains['os_family'] == 'RedHat' %}
> > ```
> 
> To be concrete, the salt states on sunaform use this text as family ;)

OK. But at least we're compatible with existing sumaform...

**Comment by juliogonzalez** [comment]
https://gitlab.suse.de/juliogonzalezgil/terracumber/-/merge_requests/7 is merged, so the original repo can be used again (moving to Uyuni will take some time, there are some final changes I want to do first)

**Comment by Bischoff** [comment]
> https://gitlab.suse.de/juliogonzalezgil/terracumber/-/merge_requests/7 is merged, so the original repo can be used again

Cool @juliogonzalez . I'm on vacation but I will create the PR now, it's the matter of 10 minutes.

> (moving to Uyuni will take some time, there are some final changes I want to do first)

No worries.

**Comment by Bischoff** [comment]
Back to your repository in #102.

**Pull request merged**
