### PR TITLE
Use hexagon environment to test Uyuni 2020.07 fixes

### PR DESCRIPTION
**Pull request by juliogonzalez**

### CODE REVIEW

**Review by moio — CHANGES_REQUESTED** [review]
I think this line needs changing too 

https://github.com/SUSE/susemanager-ci/pull/118/files#diff-3f5d9dc28a58069171660f28ab314e18R84

**Comment by juliogonzalez** [comment]
True! Fixed now :-)

**Review by moio — COMMENTED** [review]
Just noticed, the image list might also need tweaking, as opensuse152o is not there

**Comment by juliogonzalez** [comment]
Added

**Review by moio — APPROVED** [review]

**Pull request merged**
